Gentoo: Disable failing test ld-x86-64/x86-64.exp pie1.d
The reason why it fails is (surprise) a textrel warning, but in this case
some other warning creeps in and it doesnt fit our regexp anymore.
There's a limit how much I care. Example test log below.

/var/tmp/portage/sys-devel/binutils-2.29.1-r1/work/build/ld/../gas/as-new  --64  -o tmpdir/pie1.o
/var/tmp/portage/sys-devel/binutils-2.29.1-r1/work/binutils-2.29.1/ld/testsuite/ld-x86-64/pie1.s
Executing on host: sh -c {/var/tmp/portage/sys-devel/binutils-2.29.1-r1/work/build/ld/../gas/as-new  --64  -o tmpdir/pie1.o
/var/tmp/portage/sys-devel/binutils-2.29.1-r1/work/binutils-2.29.1/ld/tes
tsuite/ld-x86-64/pie1.s 2>&1}  /dev/null ld.tmp (timeout = 300)
spawn [open ...]
./ld-new --hash-style=sysv -z norelro  -L/var/tmp/portage/sys-devel/binutils-2.29.1-r1/work/binutils-2.29.1/ld/testsuite/ld-x86-64  -pie -melf_x86_64 --noinhibit-exec -o tmpdir/dump
tmpdir/pie1.o
Executing on host: sh -c {./ld-new --hash-style=sysv -z norelro  -L/var/tmp/portage/sys-devel/binutils-2.29.1-r1/work/binutils-2.29.1/ld/testsuite/ld-x86-64  -pie -melf_x86_64
--noinhibit-exec -o t
mpdir/dump tmpdir/pie1.o  2>&1}  /dev/null ld.tmp (timeout = 300)
spawn [open ...]
/var/tmp/portage/sys-devel/binutils-2.29.1-r1/work/build/ld/.libs/ld-new: tmpdir/pie1.o: warning: relocation against `foo' in readonly section `.text'
tmpdir/pie1.o: In function `_start':
(.text+0x2): undefined reference to `foo'
/var/tmp/portage/sys-devel/binutils-2.29.1-r1/work/build/ld/.libs/ld-new: warning: creating a DT_TEXTREL in a shared object.
succeeded with: </var/tmp/portage/sys-devel/binutils-2.29.1-r1/work/build/ld/.libs/ld-new: tmpdir/pie1.o: warning: relocation against `foo' in readonly section `.text'
tmpdir/pie1.o: In function `_start':
(.text+0x2): undefined reference to `foo'
/var/tmp/portage/sys-devel/binutils-2.29.1-r1/work/build/ld/.libs/ld-new: warning: creating a DT_TEXTREL in a shared object.>, expected: <\A[^\n]*\.o[^\n]*In function `_start':\n[^\n]*:
undefined r
eference to `foo'\Z>
/var/tmp/portage/sys-devel/binutils-2.29.1-r1/work/build/ld/.libs/ld-new: tmpdir/pie1.o: warning: relocation against `foo' in readonly section `.text'
tmpdir/pie1.o: In function `_start':
(.text+0x2): undefined reference to `foo'
/var/tmp/portage/sys-devel/binutils-2.29.1-r1/work/build/ld/.libs/ld-new: warning: creating a DT_TEXTREL in a shared object.
FAIL: PIE with undefined symbol