Fix parens in ld bootstrap.exp
Seen with tcl 8.5.13:
ERROR: tcl error sourcing .../ld/testsuite/ld-bootstrap/bootstrap.exp.
ERROR: expected boolean value but got " [istarget ia64-*-elf*] || [istarget ia64-*-linux*"
    while executing
"if { "$flags" == "--static" && { [istarget ia64-*-elf*] || [istarget ia64-*-linux*] }
	 || [istarget mips*-*-linux*] } {
	# On ia64 and mips, tmpdir/l..."

	* testsuite/ld-bootstrap/bootstrap.exp: Use parentheses rather
	than curly braces in logical expression.

(cherry picked from commit 6bb75436cd430556060e1526777eb0bb1e00c521)
Signed-off-by: Andreas K. Hüttel <dilfridge@gentoo.org>